Moved SG shutdown to end

diff --git a/labFinish b/labFinish
--- a/labFinish
+++ b/labFinish
@@ -145,10 +145,13 @@ else
    ARRAY=($(aws ec2 describe-regions --query Regions[*].RegionName --output text --profile $profile))
 fi
 
+ARRAY=("us-east-1" "${ARRAY[@]}")
+
 for region in "${ARRAY[@]}"
 do
 
    printf "."
+   #printf "$region\n"
 
    # Tell the aws cli to use a region. The region is whichever region we are currently on in the array above. 
    aws configure set region $region --profile $profile
@@ -175,7 +178,7 @@ do
       aws ec2 terminate-instances --instance-ids $INSTANCES_STRING --profile $profile
       if [ $? -ne 0 ]
       then
-        printf "FAILED to terminate all Instancese in $region\n"
+        printf "FAILED to terminate all Instances in $region\n"
         printf "Try re-running the script again in a few seconds\n"
         return 1
       fi
@@ -322,71 +325,54 @@ do
          fi
       done
 
-
-      # Here we delete all Security Groups except for the default one as it can't be deleted and would cause an error
-      SECGROUPS=($(aws ec2 describe-security-groups --query 'SecurityGroups[?GroupName!=`default`].GroupId' --output text --profile $profile))
-
-      # Counter used to count how many times we've tried to delete a Security Group
-      cfcntr=0
-      for secgroup in "${SECGROUPS[@]}"
-      do
-        if [ $secgroup != "default" ]
-         then
-
-            # Sometimes deleting a security group will fail if something refers to it
-            # Usually it's a instance that hasn't fully terminated yet
-            # If the security group deletion fails we will wait and try angain 10 times
-            printf "Deleting the Security Group $secgroup\n"
-            aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile > /dev/null 2>&1
-            # Capture any errors as actOut
-            actOut=$?
-            # If there are errors then wait 5 seconds and try again
-            #  We will do this 10 times
-            while [[ $actOut -ne 0 && $cfcntr -le 10 ]]
-            do
-              printf "."
-              sleep 30
-              aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile > /dev/null
-              actOut=$?
-              if [ $actOut -eq 0 ]
-              then
-                break
-              fi
-              printf "."
-              cfcntr=$[$cfcntr +1]
-            done
-         fi
-      done
-
-      # If we tried 10 times and it's still not answering then we try one more time but print the error to the screen and exit if it fails again 
-      if [ $cfcntr -gt 10 ]
-      then
-        aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile
-	if [ $? -ne 0 ]
-        then
-           printf "Error occured removing the Security Group $secgroup\n"
-           printf "Try re-running the script again in a few seconds\n"
-           return 1
-        fi
-      fi
-
-#      # Here we delete all Security Groups except for the default one as it can't be deleted and would cause an error
-#      SECGROUPS=($(aws ec2 describe-security-groups --query 'SecurityGroups[?GroupName!=`default`].GroupId' --output text --profile $profile))
-#   
-#      for secgroup in "${SECGROUPS[@]}"
-#      do
-#         if [ $secgroup != "default" ]
-#         then
-#            printf "\nDeleting the Security Group $secgroup\n"
-#            aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile
-#            if [ $? -ne 0 ]
-#            then
-#               printf "Error occured removing the Security Group $secgroup\n"
-#               exit 1
-#           fi
-#         fi
-#      done
    done
+
+   # Here we delete all Security Groups except for the default one as it can't be deleted and would cause an error
+   SECGROUPS=($(aws ec2 describe-security-groups --query 'SecurityGroups[?GroupName!=`default`].GroupId' --output text --profile $profile))
+
+   # Counter used to count how many times we've tried to delete a Security Group
+   cfcntr=0
+   for secgroup in "${SECGROUPS[@]}"
+   do
+     if [ $secgroup != "default" ]
+      then
+
+         # Sometimes deleting a security group will fail if something refers to it
+         # Usually it's a instance that hasn't fully terminated yet
+         # If the security group deletion fails we will wait and try angain 10 times
+         printf "Deleting the Security Group $secgroup\n"
+         aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile > /dev/null 2>&1
+         # Capture any errors as actOut
+         actOut=$?
+         # If there are errors then wait 5 seconds and try again
+         #  We will do this 10 times
+         while [[ $actOut -ne 0 && $cfcntr -le 10 ]]
+         do
+           printf "."
+           sleep 30
+           aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile > /dev/null
+           actOut=$?
+           if [ $actOut -eq 0 ]
+           then
+             break
+           fi
+           printf "."
+           cfcntr=$[$cfcntr +1]
+         done
+      fi
+   done
+
+   # If we tried 10 times and it's still not answering then we try one more time but print the error to the screen and exit if it fails again 
+   if [ $cfcntr -gt 10 ]
+   then
+     aws ec2 delete-security-group --group-id $secgroup --output text --profile $profile
+     if [ $? -ne 0 ]
+     then
+        printf "Error occured removing the Security Group $secgroup\n"
+        printf "Try re-running the script again in a few seconds\n"
+        return 1
+     fi
+   fi
    
    # Here we delete all roles except for the built in ones which can't be deleted and would cause an error
    # When delting a role you also have to detach/delete any policies or profiles it has 
