Added scripts to create new Orgs and update AMI permissions

diff --git a/labStart b/labStart
--- a/labStart
+++ b/labStart
@@ -447,7 +447,7 @@ deploy_template () {
    done
    printf "\n$stackName started\n"
 
-# End of deploy_sensor function
+# End of deploy_template function
 }
 
 # Choose the appropriate CloudFormation json
@@ -466,6 +466,25 @@ then
 
   deploy_template "$course-$tag" $url "$parameter"
 
+fi
+
+if [ "$sensor" = "yes" ] || [ "$sensor" = "y" ]
+then
+  url="https://s3.amazonaws.com/downloads.alienvault.cloud/usm-anywhere/sensor-images/usm-anywhere-sensor-aws-vpc.template"
+
+  # The sensor cloudformatin template is provided by AlienVault. To deploy it it needs
+  # A Key - Which we will have to create
+  # The VPC ID - Each Sub Org has a different VPC ID. The Cloudformation template needs to know which VPC to deploy into so we need to grab the VPC ID first
+  # The NodeName - We will just call it Sensor
+  # The SubnetID - Each Sub Org has a different SubnetID. The Cloudfomration template needs to know which Subnet to deploy into so we need to grab the Subnet ID first
+
+  # Creating the key
+  aws ec2 create-key-pair --key-name Sensor --profile $profile > /dev/null 2>&1
+  if [ $? -ne 0 ]
+  then
+    printf "Failed to create SSH Key\n" | tee error-$profile-$stackName.txt /var/log/labs/error/error-$profile-$stackName.log
+    sendEmail.py -r USM-Anywhere-Training@alienvault.com -s "$profile Failed to Start" -b "Do not reply to this e-mail<br/>The labStart script tried to start $profilee and failed.<br/>The SSH key for the sensor could not be created<br/>Manual intervention is required<br/>"
+  exit 1
 fi
 
 if [ "$course" = "ANYSA" ]
@@ -495,30 +514,11 @@ then
   vpcid=$(aws ec2 describe-vpcs --filters Name=isDefault,Values=false --query Vpcs[*].VpcId --output=text --profile $profile)
 
   # Build the parameter variable for the course
-  parameter="ParameterKey=TrainingVPC,ParameterValue=$vpcid ParameterKey=userPassword,ParameterValue=$userPassword ParameterKey=account,ParameterValue=$accName"
+  parameter="ParameterKey=TrainingVPC,ParameterValue=$vpcid ParameterKey=HTML5Password,ParameterValue=$userPassword"
   
   deploy_template "$course-$tag" $url "$parameter"
 
 fi
-
-if [ "$sensor" = "yes" ] || [ "$sensor" = "y" ]
-then
-  url="https://s3.amazonaws.com/downloads.alienvault.cloud/usm-anywhere/sensor-images/usm-anywhere-sensor-aws-vpc.template"
-
-  # The sensor cloudformatin template is provided by AlienVault. To deploy it it needs
-  # A Key - Which we will have to create
-  # The VPC ID - Each Sub Org has a different VPC ID. The Cloudformation template needs to know which VPC to deploy into so we need to grab the VPC ID first
-  # The NodeName - We will just call it Sensor
-  # The SubnetID - Each Sub Org has a different SubnetID. The Cloudfomration template needs to know which Subnet to deploy into so we need to grab the Subnet ID first
-
-  # Creating the key
-  aws ec2 create-key-pair --key-name Sensor --profile $profile > /dev/null 2>&1
-  if [ $? -ne 0 ]
-  then
-    printf "Failed to create SSH Key\n" | tee error-$profile-$stackName.txt /var/log/labs/error/error-$profile-$stackName.log
-    sendEmail.py -r USM-Anywhere-Training@alienvault.com -s "$profile Failed to Start" -b "Do not reply to this e-mail<br/>The labStart script tried to start $profilee and failed.<br/>The SSH key for the sensor could not be created<br/>Manual intervention is required<br/>"
-  exit 1
-  fi
 
   # Getting the VPC ID
   vpcid=$(aws ec2 describe-vpcs --filters Name=isDefault,Values=false --query Vpcs[*].VpcId --output=text --profile $profile)
